package main

import (
	"encoding/json"
	"fmt"
	"os"
	"runtime"
	"slices"
	"strings"

	"github.com/spf13/pflag"
)

var version = "dev"

// blockRef represents a reference from one block to another.
type blockRef struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

// blockInfo represents a single block and all blocks it references.
type blockInfo struct {
	Name string     `json:"name"`
	Type string     `json:"type"`
	Use  []blockRef `json:"use"`
}

// blockNode is the internal representation of a block used for tree building.
type blockNode struct {
	Type string
	Use  []string
}

const (
	pipe  = "│"
	tee   = "├"
	elbow = "└"
	dash  = "─"
)

// treeParams carries parameters for a single recursive call to buildTree.
type treeParams struct {
	Name         string
	Ancestors    []string
	Indent       string
	IsLast       bool
	Depth        int
	MaxDepth     int
	TypeFilter   []string
	BlockMap     map[string]blockNode
	CircularRefs *[]string
}

// buildTree recursively builds the visual tree lines for a given block.
// It returns a slice of formatted strings with box-drawing characters.
// Circular references (self-reference, child→parent, child→grandparent) are
// silently skipped; warnings are collected in p.CircularRefs if non-nil.
func buildTree(p treeParams) []string {
	if slices.Contains(p.Ancestors, p.Name) {
		if p.CircularRefs != nil {
			path := strings.Join(append(p.Ancestors, p.Name), " -> ")
			*p.CircularRefs = append(*p.CircularRefs, path)
		}
		return nil
	}

	var connector string
	if p.Depth > 0 {
		if p.IsLast {
			connector = elbow + dash + dash + " "
		} else {
			connector = tee + dash + dash + " "
		}
	}

	lines := []string{p.Indent + connector + p.Name}

	node, ok := p.BlockMap[p.Name]
	if !ok {
		return lines
	}

	children := node.Use
	if len(p.TypeFilter) > 0 {
		var filtered []string
		for _, child := range children {
			if cn, ok := p.BlockMap[child]; ok && slices.Contains(p.TypeFilter, cn.Type) {
				filtered = append(filtered, child)
			}
		}
		children = filtered
	}

	var childIndent string
	switch {
	case p.Depth == 0:
		childIndent = ""
	case p.IsLast:
		childIndent = p.Indent + "    "
	default:
		childIndent = p.Indent + pipe + "   "
	}

	for j, child := range children {
		if p.MaxDepth > 0 && p.Depth >= p.MaxDepth {
			break
		}
		childLines := buildTree(treeParams{
			Name:         child,
			Ancestors:    append(p.Ancestors, p.Name),
			Indent:       childIndent,
			IsLast:       j == len(children)-1,
			Depth:        p.Depth + 1,
			MaxDepth:     p.MaxDepth,
			TypeFilter:   p.TypeFilter,
			BlockMap:     p.BlockMap,
			CircularRefs: p.CircularRefs,
		})
		lines = append(lines, childLines...)
	}

	return lines
}

// cliFlags holds the parsed command-line flag values.
type cliFlags struct {
	inputFile   string
	entry       string
	outputFile  string
	typeFilter  string
	level       int
	help        bool
	showVersion bool
}

// parseFlags registers and parses command-line flags using pflag.
func parseFlags() cliFlags {
	var f cliFlags
	pflag.StringVarP(&f.inputFile, "input-file", "i", "", "Path to the JSON call graph file")
	pflag.StringVarP(&f.entry, "entry", "e", "", "Comma-separated entry block names")
	pflag.StringVarP(&f.outputFile, "output-file", "o", "", "File path to write output (default: print to console)")
	pflag.StringVarP(&f.typeFilter, "type", "t", "", "Comma-separated block types to filter (e.g. FB,FC,DB,OB,UDT)")
	pflag.IntVarP(&f.level, "level", "l", 0, "Maximum expansion depth (0 = unlimited)")
	pflag.BoolVarP(&f.help, "help", "h", false, "Show this help message")
	pflag.BoolVarP(&f.showVersion, "version", "v", false, "Show version")

	pflag.Usage = func() {
		fmt.Fprint(os.Stderr, `Usage: tia-tree-calls [flags]

Description:
  Reads a block call graph (generated by tia-scan-calls) and outputs a visual
  tree of the call hierarchy, showing only block names.

Flags:
  -i, --input-file <path>   Path to the JSON call graph file
  -e, --entry <name,...>    Comma-separated entry block names.
                            If omitted, shows all top-level blocks (not called by any other block).
  -o, --output-file <path>  File path to write output. If omitted, prints to console.
  -t, --type <type,...>     Comma-separated block types to filter (e.g. FB, FC, DB, OB, UDT).
                            If omitted, all types are included.
  -l, --level <n>           Maximum expansion depth: 1=direct children, 2=grandchildren, etc.
                            0 = unlimited recursive expansion (default).
  -v, --version             Show version
  -h, --help                Show this help message.

Examples:
  tia-tree-calls -i custom.json
  tia-tree-calls -i custom.json -o tree.txt  
  tia-tree-calls -i custom.json -o tree.txt -e OB_Main -l 3 -t FB
`)
	}
	pflag.Parse()
	return f
}

// readBlocks reads and parses a JSON call graph file into a slice of blockInfo.
func readBlocks(inputFile string) ([]blockInfo, error) {
	data, err := os.ReadFile(inputFile)
	if err != nil {
		return nil, fmt.Errorf("error reading input file %q: %w", inputFile, err)
	}

	var blocks []blockInfo
	if err := json.Unmarshal(data, &blocks); err != nil {
		return nil, fmt.Errorf("error parsing JSON: %w", err)
	}
	return blocks, nil
}

// buildBlockMap converts a slice of blockInfo into a name-keyed map of blockNode,
// discarding per-reference type information.
func buildBlockMap(blocks []blockInfo) map[string]blockNode {
	blockMap := make(map[string]blockNode, len(blocks))
	for _, b := range blocks {
		names := make([]string, len(b.Use))
		for i, ref := range b.Use {
			names[i] = ref.Name
		}
		blockMap[b.Name] = blockNode{Type: b.Type, Use: names}
	}
	return blockMap
}

// resolveEntries determines the entry point blocks for the tree display.
// If entryFlag is set, it parses the comma-separated names; otherwise it finds
// top-level blocks (blocks not called by any other block). Supports type filtering
// and deduplication.
func resolveEntries(
	entryFlag string,
	blocks []blockInfo,
	blockMap map[string]blockNode,
	typeFilter []string,
) []string {
	// intentionally nil — entries are built with append in either branch
	var entries []string

	if entryFlag != "" {
		for _, e := range strings.Split(entryFlag, ",") {
			entries = append(entries, strings.TrimSpace(e))
		}
	} else {
		calledBy := make(map[string]bool)
		for _, b := range blocks {
			for _, ref := range b.Use {
				calledBy[ref.Name] = true
			}
		}
		for name := range blockMap {
			if !calledBy[name] {
				entries = append(entries, name)
			}
		}
		slices.Sort(entries)
	}

	if len(typeFilter) > 0 {
		filtered := entries[:0]
		for _, e := range entries {
			if node, ok := blockMap[e]; ok && slices.Contains(typeFilter, node.Type) {
				filtered = append(filtered, e)
			}
		}
		entries = filtered
	}

	seen := make(map[string]bool, len(entries))
	unique := make([]string, 0, len(entries))
	for _, e := range entries {
		if !seen[e] {
			seen[e] = true
			unique = append(unique, e)
		}
	}
	return unique
}

// run executes the core tree-building logic. It prints errors to stderr
// and returns a non-nil error on failure; main() uses the error to exit.
func run(f cliFlags) error {
	if f.level < 0 {
		fmt.Fprintln(os.Stderr, "Error: --level (-l) must be >= 0")
		pflag.Usage()
		return errPrinted
	}

	if f.inputFile == "" {
		fmt.Fprintln(os.Stderr, "Error: --input-file (-i) is required")
		pflag.Usage()
		return errPrinted
	}

	blocks, err := readBlocks(f.inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		return errPrinted
	}

	blockMap := buildBlockMap(blocks)

	var typeFilter []string
	if f.typeFilter != "" {
		for _, t := range strings.Split(f.typeFilter, ",") {
			typeFilter = append(typeFilter, strings.TrimSpace(t))
		}
	}

	entries := resolveEntries(f.entry, blocks, blockMap, typeFilter)

	if len(entries) == 0 && len(typeFilter) > 0 {
		fmt.Fprintln(os.Stderr, "Error: no blocks match the specified type filter")
		return errPrinted
	}

	var allLines []string
	var circularRefs []string
	for i, entry := range entries {
		if _, ok := blockMap[entry]; !ok {
			fmt.Fprintf(
				os.Stderr,
				"Warning: entry block not found in call graph: %q\n",
				entry,
			)
			continue
		}
		lines := buildTree(treeParams{
			Name:         entry,
			Ancestors:    nil,
			Indent:       "",
			IsLast:       false,
			Depth:        0,
			MaxDepth:     f.level,
			TypeFilter:   typeFilter,
			BlockMap:     blockMap,
			CircularRefs: &circularRefs,
		})
		allLines = append(allLines, lines...)
		if i < len(entries)-1 {
			allLines = append(allLines, "")
		}
	}

	if len(circularRefs) > 0 {
		fmt.Fprintf(os.Stderr, "\nWarning: circular reference(s) detected, skipped:\n")
		for _, ref := range circularRefs {
			fmt.Fprintf(os.Stderr, "  %s\n", ref)
		}
	}

	var output string
	if f.outputFile != "" && runtime.GOOS == "windows" {
		output = strings.Join(allLines, "\r\n")
	} else {
		output = strings.Join(allLines, "\n")
	}

	if f.outputFile != "" {
		if err := os.WriteFile(f.outputFile, []byte(output), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing output file: %v\n", err)
			return errPrinted
		}
		fmt.Printf("Written to %s\n", f.outputFile)
	} else {
		fmt.Println()
		fmt.Println(output)
	}
	return nil
}

// errPrinted is returned by run() when the error message has already been
// written to stderr. main() treats it as "exit with code 1".
var errPrinted = fmt.Errorf("")

func main() {
	f := parseFlags()
	if f.showVersion {
		fmt.Printf("tia-tree-calls %s\n", version)
		return
	}
	if f.help {
		pflag.Usage()
		return
	}
	if err := run(f); err != nil {
		os.Exit(1)
	}
}
