package main

import (
	"encoding/json"
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/spf13/pflag"
)

var version string

type blockRef struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type blockInfo struct {
	Name string     `json:"name"`
	Type string     `json:"type"`
	Use  []blockRef `json:"use"`
}

type blockNode struct {
	Type string
	Use  []string
}

const (
	pipe  = "│"
	tee   = "├"
	elbow = "└"
	dash  = "─"
)

type treeParams struct {
	Name       string
	Ancestors  []string
	Indent     string
	IsLast     bool
	Depth      int
	MaxDepth   int
	TypeFilter []string
	BlockMap   map[string]blockNode
}

func buildTree(p treeParams) []string {
	var connector string
	if p.Depth > 0 {
		if p.IsLast {
			connector = elbow + dash + dash + " "
		} else {
			connector = tee + dash + dash + " "
		}
	}

	lines := []string{p.Indent + connector + p.Name}

	if slices.Contains(p.Ancestors, p.Name) {
		return lines
	}

	node, ok := p.BlockMap[p.Name]
	if !ok {
		return lines
	}

	children := node.Use
	if len(p.TypeFilter) > 0 {
		var filtered []string
		for _, child := range children {
			if cn, ok := p.BlockMap[child]; ok && slices.Contains(p.TypeFilter, cn.Type) {
				filtered = append(filtered, child)
			}
		}
		children = filtered
	}

	var childIndent string
	switch {
	case p.Depth == 0:
		childIndent = ""
	case p.IsLast:
		childIndent = p.Indent + "    "
	default:
		childIndent = p.Indent + pipe + "   "
	}

	for j, child := range children {
		if p.MaxDepth > 0 && p.Depth >= p.MaxDepth {
			break
		}
		childLines := buildTree(treeParams{
			Name:       child,
			Ancestors:  append(p.Ancestors, p.Name),
			Indent:     childIndent,
			IsLast:     j == len(children)-1,
			Depth:      p.Depth + 1,
			MaxDepth:   p.MaxDepth,
			TypeFilter: p.TypeFilter,
			BlockMap:   p.BlockMap,
		})
		lines = append(lines, childLines...)
	}

	return lines
}

type cliFlags struct {
	inputFile   string
	entry       string
	outputFile  string
	typeFilter  string
	level       int
	help        bool
	showVersion bool
}

func parseFlags() cliFlags {
	var f cliFlags
	pflag.StringVarP(&f.inputFile, "input-file", "i", "", "Path to the JSON call graph file")
	pflag.StringVarP(&f.entry, "entry", "e", "", "Comma-separated entry block names")
	pflag.StringVarP(&f.outputFile, "output-file", "o", "", "File path to write output (default: print to console)")
	pflag.StringVarP(&f.typeFilter, "type", "t", "", "Comma-separated block types to filter (e.g. FB,FC,DB,OB,UDT)")
	pflag.IntVarP(&f.level, "level", "l", 0, "Maximum expansion depth (0 = unlimited)")
	pflag.BoolVarP(&f.help, "help", "h", false, "Show this help message")
	pflag.BoolVarP(&f.showVersion, "version", "v", false, "Show version")

	pflag.Usage = func() {
		fmt.Fprint(os.Stderr, `Usage: tia-tree-calls [flags]

Description:
  Reads a block call graph (generated by tia-tree-calls) and outputs a visual
  tree of the call hierarchy, showing only block names.

Flags:
  -i, --input-file <path>   Path to the JSON call graph file
  -e, --entry <name,...>    Comma-separated entry block names.
                            If omitted, shows all top-level blocks (not called by any other block).
  -o, --output-file <path>  File path to write output. If omitted, prints to console.
  -t, --type <type,...>     Comma-separated block types to filter (e.g. FB, FC, DB, OB, UDT).
                            If omitted, all types are included.
  -l, --level <n>           Maximum expansion depth: 1=direct children, 2=grandchildren, etc.
                            0 = unlimited recursive expansion (default).
  -v, --version             Show version
  -h, --help                Show this help message.

Examples:
  tia-tree-calls --entry OB_Program_Cycle
  tia-tree-calls -e FB_Bin_Control,FB_Hoist_Control -l 1
  tia-tree-calls -t FB,FC
  tia-tree-calls -l 2
  tia-tree-calls -e OB_Main -l 3 -t FB
  tia-tree-calls -i custom.json -o tree.txt
`)
	}
	pflag.Parse()
	return f
}

func readBlocks(inputFile string) ([]blockInfo, error) {
	data, err := os.ReadFile(inputFile)
	if err != nil {
		return nil, fmt.Errorf("error reading input file %q: %w", inputFile, err)
	}

	var blocks []blockInfo
	if err := json.Unmarshal(data, &blocks); err != nil {
		return nil, fmt.Errorf("error parsing JSON: %w", err)
	}
	return blocks, nil
}

func buildBlockMap(blocks []blockInfo) map[string]blockNode {
	blockMap := make(map[string]blockNode, len(blocks))
	for _, b := range blocks {
		names := make([]string, len(b.Use))
		for i, ref := range b.Use {
			names[i] = ref.Name
		}
		blockMap[b.Name] = blockNode{Type: b.Type, Use: names}
	}
	return blockMap
}

func resolveEntries(
	entryFlag string,
	blocks []blockInfo,
	blockMap map[string]blockNode,
	typeFilter []string,
) []string {
	// intentionally nil — entries are built with append in either branch
	var entries []string

	if entryFlag != "" {
		for _, e := range strings.Split(entryFlag, ",") {
			entries = append(entries, strings.TrimSpace(e))
		}
	} else {
		calledBy := make(map[string]bool)
		for _, b := range blocks {
			for _, ref := range b.Use {
				calledBy[ref.Name] = true
			}
		}
		for name := range blockMap {
			if !calledBy[name] {
				entries = append(entries, name)
			}
		}
		slices.Sort(entries)
	}

	if len(typeFilter) > 0 {
		filtered := entries[:0]
		for _, e := range entries {
			if node, ok := blockMap[e]; ok && slices.Contains(typeFilter, node.Type) {
				filtered = append(filtered, e)
			}
		}
		entries = filtered
	}

	seen := make(map[string]bool, len(entries))
	unique := make([]string, 0, len(entries))
	for _, e := range entries {
		if !seen[e] {
			seen[e] = true
			unique = append(unique, e)
		}
	}
	return unique
}

func main() {
	f := parseFlags()
	if f.showVersion {
		fmt.Printf("tia-tree-calls %s\n", version)
		return
	}
	if f.help {
		pflag.Usage()
		return
	}

	blocks, err := readBlocks(f.inputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}

	blockMap := buildBlockMap(blocks)

	// intentionally nil — type filtering is applied inside resolveEntries
	var typeFilter []string
	if f.typeFilter != "" {
		for _, t := range strings.Split(f.typeFilter, ",") {
			typeFilter = append(typeFilter, strings.TrimSpace(t))
		}
	}

	entries := resolveEntries(f.entry, blocks, blockMap, typeFilter)

	var allLines []string
	for i, entry := range entries {
		if _, ok := blockMap[entry]; !ok {
			fmt.Fprintf(
				os.Stderr,
				"Warning: entry block not found in call graph: %q\n",
				entry,
			)
			continue
		}
		lines := buildTree(treeParams{
			Name:       entry,
			Ancestors:  nil,
			Indent:     "",
			IsLast:     false,
			Depth:      0,
			MaxDepth:   f.level,
			TypeFilter: typeFilter,
			BlockMap:   blockMap,
		})
		allLines = append(allLines, lines...)
		if i < len(entries)-1 {
			allLines = append(allLines, "")
		}
	}

	output := strings.Join(allLines, "\r\n")

	if f.outputFile != "" {
		if err := os.WriteFile(f.outputFile, []byte(output), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing output file: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("Written to %s\n", f.outputFile)
	} else {
		fmt.Println()
		fmt.Println(output)
	}
}
